#!/usr/bin/env python3
"""
train_windowseat.py
--------------------
Phase 1 training script for WindowSeat reflection removal.
Fine-tunes LoRA adapters on the Qwen-Image-Edit-2509 DiT backbone
using flow matching loss in latent space.

No text conditioning in Phase 1 — a fixed learned task embedding
is used (same as the released model). Phase 2 text guidance is
a natural extension of this script.

Architecture
------------
  Qwen-Image-Edit-2509 (frozen)
    ├── AutoencoderKLQwenImage (frozen VAE — encodes/decodes images)
    └── QwenImageTransformer2DModel (frozen DiT backbone)
            └── LoRA adapters (trainable)
  Fixed task embedding (trainable — small MLP initialised from scratch)

Training objective (flow matching)
-----------------------------------
  target_velocity = encode(clean) - encode(reflected)
  predicted_velocity = transformer(encode(reflected), t=499, task_embed)
  loss = MSE(predicted_velocity, target_velocity)

With optional perceptual loss:
  loss += lambda_lpips * LPIPS(decode(predicted_latent), clean_image)

where predicted_latent = encode(reflected) - predicted_velocity

Dataset structure expected on disk
-----------------------------------
  data/
    train/
      synthetic/
        blended/   <- reflected images (auto-generated by blend_dataset.py)
        clean/     <- ground truth clean images
      real/
        blended/   <- real reflected images (from SIR2 train split)
        clean/     <- real clean images
    val/
      real/
        blended/
        clean/
    test/          <- NEVER touched during training
      nature/
      real20/
      sir2_500/

Usage
-----
  # Single GPU
  python train_windowseat.py --data-root data/ --output-dir runs/baseline

  # Multi-GPU with torchrun
  torchrun --nproc_per_node=4 train_windowseat.py \\
      --data-root data/ --output-dir runs/baseline --batch-size 4

  # Resume from checkpoint
  python train_windowseat.py --data-root data/ --output-dir runs/baseline \\
      --resume runs/baseline/checkpoint_epoch5.pt
"""

import argparse
import json
import math
import os
import random
from pathlib import Path

import lpips as lpips_lib
import numpy as np
import torch
import torch.distributed as dist
import torch.nn.functional as F
import torchvision.transforms.functional as TF
import wandb
from diffusers import (
    AutoencoderKLQwenImage,
    QwenImageEditPipeline,
    QwenImageTransformer2DModel,
)
from huggingface_hub import hf_hub_download
from peft import LoraConfig, get_peft_model
from PIL import Image
from skimage.metrics import peak_signal_noise_ratio as compute_psnr
from skimage.metrics import structural_similarity as compute_ssim
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, Dataset, DistributedSampler
from tqdm import tqdm


# ── Defaults  ─────────────────────────────────────────────────────────────────

BASE_MODEL_URI  = "Qwen/Qwen-Image-Edit-2509"
FIXED_TIMESTEP  = 499          # WindowSeat uses a single fixed timestep
VAE_SCALE       = 8            # spatial downsampling factor of the VAE


# ── Args  ─────────────────────────────────────────────────────────────────────

def get_args():
    p = argparse.ArgumentParser(
        description="Train WindowSeat LoRA for reflection removal",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Paths
    p.add_argument("--data-root",    required=True,  help="Root of dataset directory")
    p.add_argument("--output-dir",   required=True,  help="Where to save checkpoints and logs")
    p.add_argument("--resume",       default=None,   help="Path to checkpoint to resume from")

    # Model
    p.add_argument("--base-model",   default=BASE_MODEL_URI)
    p.add_argument("--lora-rank",    type=int, default=64,   help="LoRA rank r")
    p.add_argument("--lora-alpha",   type=int, default=64,   help="LoRA alpha (scaling = alpha/r)")
    p.add_argument("--lora-dropout", type=float, default=0.05)

    # Training
    p.add_argument("--epochs",       type=int,   default=20)
    p.add_argument("--batch-size",   type=int,   default=4,    help="Per-GPU batch size")
    p.add_argument("--grad-accum",   type=int,   default=4,    help="Gradient accumulation steps")
    p.add_argument("--lr",           type=float, default=1e-4)
    p.add_argument("--lr-embed",     type=float, default=1e-3, help="LR for task embedding")
    p.add_argument("--weight-decay", type=float, default=0.01)
    p.add_argument("--warmup-steps", type=int,   default=500)
    p.add_argument("--max-grad-norm",type=float, default=1.0)
    p.add_argument("--resolution",   type=int,   default=768,  help="Training crop size")

    # Loss
    p.add_argument("--lambda-lpips", type=float, default=0.1,
                   help="Weight for LPIPS perceptual loss (0 = disabled)")

    # Logging
    p.add_argument("--log-interval",  type=int, default=50)
    p.add_argument("--val-interval",  type=int, default=1,    help="Validate every N epochs")
    p.add_argument("--save-interval", type=int, default=1,    help="Save checkpoint every N epochs")
    p.add_argument("--wandb-project", default="windowseat",   help="W&B project name ('' to disable)")
    p.add_argument("--run-name",      default=None)

    # System
    p.add_argument("--num-workers",  type=int, default=8)
    p.add_argument("--seed",         type=int, default=42)
    p.add_argument("--local-rank",   type=int, default=-1,    help="Set by torchrun automatically")

    return p.parse_args()


# ── Distributed helpers  ──────────────────────────────────────────────────────

def is_main_process():
    return not dist.is_initialized() or dist.get_rank() == 0


def setup_distributed(local_rank):
    if local_rank == -1:
        return torch.device("cuda"), 0, 1
    dist.init_process_group("nccl")
    torch.cuda.set_device(local_rank)
    return torch.device(f"cuda:{local_rank}"), dist.get_rank(), dist.get_world_size()


# ── Dataset  ──────────────────────────────────────────────────────────────────

class ReflectionPairDataset(Dataset):
    """
    Loads paired (reflected, clean) images from a directory structure:

        split/
          synthetic/blended/  +  synthetic/clean/
          real/blended/        +  real/clean/

    Images are matched by filename. Both sources are pooled together.
    Joint augmentation (same random crop + flip) is applied to keep
    reflected and clean images spatially aligned.
    """

    def __init__(self, data_root: str, split: str, resolution: int = 768):
        self.resolution = resolution
        self.pairs      = []   # list of (blended_path, clean_path)

        split_dir = Path(data_root) / split
        for subset in ("synthetic", "real"):
            blended_dir = split_dir / subset / "blended"
            clean_dir   = split_dir / subset / "clean"
            if not blended_dir.exists():
                continue
            for fname in sorted(os.listdir(blended_dir)):
                if not fname.lower().endswith((".png", ".jpg", ".jpeg")):
                    continue
                b_path = blended_dir / fname
                c_path = clean_dir   / fname
                if c_path.exists():
                    self.pairs.append((str(b_path), str(c_path)))

        print(f"  [{split}] {len(self.pairs)} pairs loaded")

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        b_path, c_path = self.pairs[idx]
        blended = Image.open(b_path).convert("RGB")
        clean   = Image.open(c_path).convert("RGB")

        # ── Joint augmentation ───────────────────────────────────────────────
        # Same random crop and flip applied to both images
        blended, clean = self._joint_augment(blended, clean)

        # Normalise to [-1, 1] as expected by the VAE
        blended = TF.to_tensor(blended) * 2.0 - 1.0   # (3, H, W)
        clean   = TF.to_tensor(clean)   * 2.0 - 1.0

        return {"blended": blended, "clean": clean}

    def _joint_augment(self, blended: Image.Image, clean: Image.Image):
        R = self.resolution

        # Resize short edge to at least R (preserving aspect ratio)
        W, H = blended.size
        if min(W, H) < R:
            scale = R / min(W, H)
            new_w, new_h = int(W * scale), int(H * scale)
            blended = blended.resize((new_w, new_h), Image.LANCZOS)
            clean   = clean.resize((new_w, new_h), Image.LANCZOS)
            W, H    = new_w, new_h

        # Random crop — same coordinates for both
        i = random.randint(0, H - R)
        j = random.randint(0, W - R)
        blended = TF.crop(blended, i, j, R, R)
        clean   = TF.crop(clean,   i, j, R, R)

        # Random horizontal flip — same decision for both
        if random.random() < 0.5:
            blended = TF.hflip(blended)
            clean   = TF.hflip(clean)

        return blended, clean


# ── Synthetic data generation  ────────────────────────────────────────────────

def blend_images(transmission: np.ndarray, reflection: np.ndarray,
                 alpha: float = None) -> np.ndarray:
    """
    Simple alpha-blending model for synthetic reflection generation.

    I_blended = alpha * I_transmission + (1 - alpha) * blur(I_reflection)

    alpha is sampled from [0.7, 0.95] if not provided.
    The reflection is slightly blurred to simulate out-of-focus reflections.
    """
    import cv2
    if alpha is None:
        alpha = random.uniform(0.7, 0.95)

    # Optionally blur the reflection
    if random.random() < 0.7:
        ksize = random.choice([3, 5, 7])
        reflection = cv2.GaussianBlur(reflection, (ksize, ksize), 0)

    blended = alpha * transmission.astype(np.float32) + \
              (1.0 - alpha) * reflection.astype(np.float32)
    return np.clip(blended, 0, 255).astype(np.uint8)


# ── Model loading  ────────────────────────────────────────────────────────────

def load_vae(uri: str, device: torch.device) -> AutoencoderKLQwenImage:
    """Load and freeze the VAE — never trained."""
    vae = AutoencoderKLQwenImage.from_pretrained(
        uri, subfolder="vae",
        torch_dtype=torch.bfloat16,
        use_safetensors=True,
    )
    vae.to(device, dtype=torch.bfloat16)
    vae.requires_grad_(False)
    vae.eval()
    return vae


def load_transformer_with_lora(
    uri: str,
    device: torch.device,
    lora_rank: int,
    lora_alpha: int,
    lora_dropout: float,
) -> QwenImageTransformer2DModel:
    """
    Load the DiT transformer in bf16 (full precision for training —
    no 4-bit quantisation here unlike inference) and attach LoRA.

    LoRA target modules: the attention projection layers inside each
    transformer block. We target q, k, v, out projections.
    """
    transformer = QwenImageTransformer2DModel.from_pretrained(
        uri,
        subfolder="transformer",
        torch_dtype=torch.bfloat16,
        device_map=device,
    )

    lora_config = LoraConfig(
        r=lora_rank,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        # Target the linear projections inside attention blocks
        target_modules=[
            "to_q", "to_k", "to_v", "to_out.0",
            "ff.net.0.proj", "ff.net.2",
        ],
        bias="none",
    )
    transformer = get_peft_model(transformer, lora_config)
    transformer.print_trainable_parameters()
    return transformer


class TaskEmbedding(torch.nn.Module):
    """
    Learnable fixed task embedding that replaces the inference-time
    loaded prompt_embeds. Initialised randomly and trained end-to-end.

    This is a small set of learned vectors — one per context token —
    that tells the transformer it is performing reflection removal.
    In Phase 2 this would be replaced by dynamic text encodings.

    Dimensions are matched to what flow_step() expects:
        prompt_embeds : (1, L, D)   L=context tokens, D=hidden dim
        prompt_mask   : (1, L)      all True (no padding)
    """
    def __init__(self, n_tokens: int = 77, hidden_dim: int = 4096):
        super().__init__()
        self.embeddings = torch.nn.Parameter(
            torch.randn(1, n_tokens, hidden_dim) * 0.02
        )
        self.register_buffer("mask", torch.ones(1, n_tokens, dtype=torch.bool))

    def forward(self, batch_size: int):
        embeds = self.embeddings.expand(batch_size, -1, -1)
        mask   = self.mask.expand(batch_size, -1)
        return embeds, mask


# ── VAE encode / decode (matches windowseat_inference.py exactly)  ─────────

@torch.no_grad()
def encode(images: torch.Tensor, vae: AutoencoderKLQwenImage) -> torch.Tensor:
    """Encode images (B,3,H,W) to latents (B,C,1,H/8,W/8)."""
    images = images.to(device=vae.device, dtype=vae.dtype)
    out    = vae.encode(images.unsqueeze(2)).latent_dist.sample()
    mean   = torch.tensor(vae.config.latents_mean,   device=out.device, dtype=out.dtype)
    std_i  = torch.tensor(vae.config.latents_std,    device=out.device, dtype=out.dtype)
    mean   = mean.view(1, vae.config.z_dim, 1, 1, 1)
    std_i  = (1.0 / std_i).view(1, vae.config.z_dim, 1, 1, 1)
    return (out - mean) * std_i


def decode(latents: torch.Tensor, vae: AutoencoderKLQwenImage) -> torch.Tensor:
    """Decode latents back to pixel space, returns (B,3,H,W) in [-1,1]."""
    mean  = torch.tensor(vae.config.latents_mean, device=latents.device, dtype=latents.dtype)
    std_i = torch.tensor(vae.config.latents_std,  device=latents.device, dtype=latents.dtype)
    mean  = mean.view(1, vae.config.z_dim, 1, 1, 1)
    std_i = (1.0 / std_i).view(1, vae.config.z_dim, 1, 1, 1)
    latents = latents / std_i + mean
    out     = vae.decode(latents)
    return out.sample[:, :, 0]   # (B, 3, H, W)


# ── Flow step (forward pass through transformer)  ────────────────────────────

def flow_step_train(
    latent_input   : torch.Tensor,
    transformer    : QwenImageTransformer2DModel,
    vae            : AutoencoderKLQwenImage,
    prompt_embeds  : torch.Tensor,
    prompt_mask    : torch.Tensor,
) -> torch.Tensor:
    """
    Single-step flow matching forward pass.
    Mirrors windowseat_inference.py flow_step() but with gradients enabled
    for LoRA parameter updates.

    Returns the predicted velocity field (same shape as latent_input).
    """
    # Handle (B,C,1,H,W) or (B,C,H,W)
    if latent_input.ndim == 5 and latent_input.shape[2] == 1:
        lat4d = latent_input[:, :, 0]
    else:
        lat4d = latent_input

    B, C, H, W = lat4d.shape
    device = next(transformer.parameters()).device

    prompt_embeds = prompt_embeds.to(device=device, dtype=torch.bfloat16)
    prompt_mask   = prompt_mask.to(device=device)

    # Pack latents into sequence of patches
    packed = QwenImageEditPipeline._pack_latents(
        lat4d, batch_size=B,
        num_channels_latents=C, height=H, width=W,
    ).to(torch.bfloat16)

    timestep = torch.full((B,), float(FIXED_TIMESTEP) / 1000.0,
                          device=device, dtype=torch.bfloat16)

    h_img, w_img  = H // 2, W // 2
    img_shapes    = [[(1, h_img, w_img)]] * B
    txt_seq_lens  = prompt_mask.sum(dim=1).tolist()

    with torch.amp.autocast("cuda", dtype=torch.bfloat16):
        model_pred = transformer(
            hidden_states=packed,
            timestep=timestep,
            encoder_hidden_states=prompt_embeds,
            encoder_hidden_states_mask=prompt_mask,
            img_shapes=img_shapes,
            txt_seq_lens=txt_seq_lens,
            guidance=None,
            return_dict=False,
        )[0]

    # Get VAE scale factor
    td = vae.config.get("temperal_downsample", None)
    sf = 2 ** len(td) if td is not None else 8

    # Unpack back to (B,C,1,H,W)
    model_pred = QwenImageEditPipeline._unpack_latents(
        model_pred,
        height=H * sf, width=W * sf,
        vae_scale_factor=sf,
    )
    return model_pred   # predicted velocity (B,C,1,H,W)


# ── Loss  ─────────────────────────────────────────────────────────────────────

class ReflectionRemovalLoss(torch.nn.Module):
    """
    Combined flow matching loss + optional LPIPS perceptual loss.

    Flow matching loss:
        velocity_target = z_reflected - z_clean
        loss_flow = MSE(predicted_velocity, velocity_target)

    Perceptual loss (optional):
        z_predicted = z_reflected - predicted_velocity
        img_predicted = decode(z_predicted)
        loss_lpips = LPIPS(img_predicted, img_clean)
    """
    def __init__(self, lambda_lpips: float = 0.1, device: torch.device = None):
        super().__init__()
        self.lambda_lpips = lambda_lpips
        if lambda_lpips > 0:
            self.lpips_net = lpips_lib.LPIPS(net="alex").to(device)
            self.lpips_net.requires_grad_(False)
            self.lpips_net.eval()
        else:
            self.lpips_net = None

    def forward(
        self,
        predicted_velocity : torch.Tensor,   # (B,C,1,H,W)
        z_reflected        : torch.Tensor,   # (B,C,1,H,W)
        z_clean            : torch.Tensor,   # (B,C,1,H,W)
        vae                : AutoencoderKLQwenImage,
        clean_images       : torch.Tensor,   # (B,3,H,W) in [-1,1], for LPIPS
    ):
        # Flow matching loss in latent space
        velocity_target = z_reflected - z_clean
        loss_flow = F.mse_loss(
            predicted_velocity.float(),
            velocity_target.float(),
        )

        loss_lpips = torch.tensor(0.0, device=predicted_velocity.device)
        if self.lpips_net is not None and self.lambda_lpips > 0:
            # Predict clean latents and decode to pixels
            with torch.no_grad():
                z_pred  = z_reflected.float() - predicted_velocity.float()
                img_pred = decode(z_pred.to(vae.dtype), vae)   # (B,3,H,W) in [-1,1]

            # LPIPS expects (B,3,H,W) in [-1,1]
            img_pred   = img_pred.float().clamp(-1, 1)
            clean_f    = clean_images.float().to(img_pred.device)
            loss_lpips = self.lpips_net(img_pred, clean_f).mean()

        total = loss_flow + self.lambda_lpips * loss_lpips
        return total, loss_flow, loss_lpips


# ── LR scheduler (cosine with warmup)  ───────────────────────────────────────

def get_scheduler(optimizer, warmup_steps: int, total_steps: int):
    def lr_lambda(step):
        if step < warmup_steps:
            return float(step) / max(1, warmup_steps)
        progress = float(step - warmup_steps) / max(1, total_steps - warmup_steps)
        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))
    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


# ── Validation  ───────────────────────────────────────────────────────────────

@torch.no_grad()
def validate(
    vae          : AutoencoderKLQwenImage,
    transformer  : QwenImageTransformer2DModel,
    task_embed   : TaskEmbedding,
    val_loader   : DataLoader,
    device       : torch.device,
    epoch        : int,
):
    """
    Runs inference on the validation set and computes PSNR and SSIM.
    Returns dict with mean metrics.
    """
    transformer.eval()
    task_embed.eval()

    psnr_vals, ssim_vals = [], []

    for batch in tqdm(val_loader, desc=f"Val epoch {epoch}", leave=False,
                      disable=not is_main_process()):
        blended = batch["blended"].to(device, dtype=torch.bfloat16)
        clean   = batch["clean"].to(device)

        B = blended.shape[0]
        prompt_embeds, prompt_mask = task_embed(B)

        # Encode
        z_reflected = encode(blended, vae)

        # Forward pass
        pred_velocity = flow_step_train(
            z_reflected, transformer, vae, prompt_embeds, prompt_mask
        )

        # Decode prediction
        z_pred   = z_reflected.float() - pred_velocity.float()
        img_pred = decode(z_pred.to(vae.dtype), vae)   # (B,3,H,W) in [-1,1]

        # Convert to [0,1] numpy for metric computation
        pred_np  = ((img_pred.float().clamp(-1, 1) + 1) / 2).cpu().numpy()
        clean_np = ((clean.float().clamp(-1, 1) + 1) / 2).cpu().numpy()

        for b in range(B):
            p = pred_np[b].transpose(1, 2, 0)    # (H,W,3)
            c = clean_np[b].transpose(1, 2, 0)
            psnr_vals.append(compute_psnr(c, p, data_range=1.0))
            try:
                ssim_vals.append(compute_ssim(c, p, data_range=1.0, channel_axis=-1))
            except TypeError:
                ssim_vals.append(compute_ssim(c, p, data_range=1.0, multichannel=True))

    transformer.train()
    task_embed.train()

    return {
        "val/psnr": float(np.mean(psnr_vals)),
        "val/ssim": float(np.mean(ssim_vals)),
    }


# ── Checkpoint  ───────────────────────────────────────────────────────────────

def save_checkpoint(output_dir, epoch, transformer, task_embed, optimizer,
                    scheduler, metrics: dict):
    os.makedirs(output_dir, exist_ok=True)
    ckpt = {
        "epoch"           : epoch,
        "lora_state_dict" : {k: v for k, v in transformer.state_dict().items()
                             if "lora" in k},
        "task_embed"      : task_embed.state_dict(),
        "optimizer"       : optimizer.state_dict(),
        "scheduler"       : scheduler.state_dict(),
        "metrics"         : metrics,
    }
    path = os.path.join(output_dir, f"checkpoint_epoch{epoch:03d}.pt")
    torch.save(ckpt, path)
    # Keep a symlink to latest
    latest = os.path.join(output_dir, "checkpoint_latest.pt")
    if os.path.exists(latest):
        os.remove(latest)
    os.symlink(os.path.basename(path), latest)
    return path


def load_checkpoint(path, transformer, task_embed, optimizer, scheduler):
    ckpt = torch.load(path, map_location="cpu")
    # Load only LoRA weights into transformer
    missing, unexpected = transformer.load_state_dict(
        ckpt["lora_state_dict"], strict=False
    )
    task_embed.load_state_dict(ckpt["task_embed"])
    optimizer.load_state_dict(ckpt["optimizer"])
    scheduler.load_state_dict(ckpt["scheduler"])
    print(f"Resumed from epoch {ckpt['epoch']}  metrics={ckpt.get('metrics', {})}")
    return ckpt["epoch"]


# ── Main  ─────────────────────────────────────────────────────────────────────

def main():
    args  = get_args()
    device, rank, world_size = setup_distributed(args.local_rank)

    # Reproducibility
    torch.manual_seed(args.seed + rank)
    random.seed(args.seed + rank)
    np.random.seed(args.seed + rank)

    os.makedirs(args.output_dir, exist_ok=True)

    # ── W&B  ──────────────────────────────────────────────────────────────────
    if is_main_process() and args.wandb_project:
        wandb.init(
            project=args.wandb_project,
            name=args.run_name or f"rank{rank}",
            config=vars(args),
        )

    # ── Data  ─────────────────────────────────────────────────────────────────
    if is_main_process():
        print("Loading datasets...")
    train_ds = ReflectionPairDataset(args.data_root, "train", args.resolution)
    val_ds   = ReflectionPairDataset(args.data_root, "val",   args.resolution)

    train_sampler = DistributedSampler(train_ds, shuffle=True) if world_size > 1 else None
    val_sampler   = DistributedSampler(val_ds,   shuffle=False) if world_size > 1 else None

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        sampler=train_sampler,
        shuffle=(train_sampler is None),
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        sampler=val_sampler,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
    )

    # ── Models  ───────────────────────────────────────────────────────────────
    if is_main_process():
        print(f"Loading base model from {args.base_model} ...")

    vae = load_vae(args.base_model, device)

    transformer = load_transformer_with_lora(
        args.base_model, device,
        lora_rank=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
    )
    transformer.train()

    # Task embedding — learnable, same role as loaded embeds_dict at inference
    # Hidden dim 4096 matches Qwen-Image-Edit-2509 transformer hidden size
    task_embed = TaskEmbedding(n_tokens=77, hidden_dim=4096).to(device)
    task_embed.train()

    if world_size > 1:
        transformer = DDP(transformer, device_ids=[args.local_rank])
        task_embed  = DDP(task_embed,  device_ids=[args.local_rank])

    # ── Loss  ─────────────────────────────────────────────────────────────────
    criterion = ReflectionRemovalLoss(lambda_lpips=args.lambda_lpips, device=device)

    # ── Optimizer — separate LRs for LoRA and task embedding  ─────────────────
    lora_params  = [p for n, p in transformer.named_parameters() if "lora" in n]
    embed_params = list(task_embed.parameters())

    optimizer = torch.optim.AdamW(
        [
            {"params": lora_params,  "lr": args.lr},
            {"params": embed_params, "lr": args.lr_embed},
        ],
        weight_decay=args.weight_decay,
    )

    total_steps = len(train_loader) // args.grad_accum * args.epochs
    scheduler   = get_scheduler(optimizer, args.warmup_steps, total_steps)

    # ── Resume  ───────────────────────────────────────────────────────────────
    start_epoch = 0
    if args.resume:
        start_epoch = load_checkpoint(
            args.resume, transformer, task_embed, optimizer, scheduler
        )

    # ── Training loop  ────────────────────────────────────────────────────────
    global_step = 0
    scaler      = torch.cuda.amp.GradScaler()   # for mixed precision

    for epoch in range(start_epoch, args.epochs):
        if train_sampler is not None:
            train_sampler.set_epoch(epoch)

        transformer.train()
        task_embed.train()

        epoch_loss  = 0.0
        optimizer.zero_grad()

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{args.epochs}",
                    disable=not is_main_process())

        for step, batch in enumerate(pbar):
            blended = batch["blended"].to(device, dtype=torch.bfloat16)
            clean   = batch["clean"].to(device,   dtype=torch.bfloat16)
            B       = blended.shape[0]

            # Get task embedding for this batch
            prompt_embeds, prompt_mask = (task_embed.module if world_size > 1
                                          else task_embed)(B)

            # ── Encode inputs (no grad — VAE is frozen) ────────────────────
            with torch.no_grad():
                z_reflected = encode(blended, vae)
                z_clean     = encode(clean,   vae)

            # ── Forward pass through transformer (grads on LoRA only) ─────
            pred_velocity = flow_step_train(
                z_reflected, transformer, vae, prompt_embeds, prompt_mask
            )

            # ── Compute loss ───────────────────────────────────────────────
            loss, loss_flow, loss_lpips = criterion(
                pred_velocity, z_reflected, z_clean, vae,
                clean_images=batch["clean"].to(device),
            )

            loss = loss / args.grad_accum
            scaler.scale(loss).backward()

            epoch_loss += loss.item() * args.grad_accum

            # ── Gradient step every grad_accum steps ──────────────────────
            if (step + 1) % args.grad_accum == 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(
                    lora_params + embed_params, args.max_grad_norm
                )
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                optimizer.zero_grad()
                global_step += 1

                if is_main_process() and global_step % args.log_interval == 0:
                    lr_now = scheduler.get_last_lr()[0]
                    log = {
                        "train/loss"      : loss_flow.item(),
                        "train/loss_lpips": loss_lpips.item(),
                        "train/lr"        : lr_now,
                        "train/step"      : global_step,
                    }
                    pbar.set_postfix(loss=f"{loss_flow.item():.4f}",
                                     lpips=f"{loss_lpips.item():.4f}",
                                     lr=f"{lr_now:.2e}")
                    if args.wandb_project:
                        wandb.log(log, step=global_step)

        # ── End of epoch ──────────────────────────────────────────────────
        if is_main_process():
            print(f"Epoch {epoch+1} — avg loss: {epoch_loss / len(train_loader):.4f}")

        metrics = {}

        # Validation
        if (epoch + 1) % args.val_interval == 0:
            metrics = validate(
                vae, transformer.module if world_size > 1 else transformer,
                task_embed.module if world_size > 1 else task_embed,
                val_loader, device, epoch + 1,
            )
            if is_main_process():
                print(f"  Val PSNR={metrics['val/psnr']:.2f}  "
                      f"SSIM={metrics['val/ssim']:.4f}")
                if args.wandb_project:
                    wandb.log(metrics, step=global_step)

        # Checkpoint
        if is_main_process() and (epoch + 1) % args.save_interval == 0:
            path = save_checkpoint(
                args.output_dir, epoch + 1,
                transformer.module if world_size > 1 else transformer,
                task_embed.module  if world_size > 1 else task_embed,
                optimizer, scheduler, metrics,
            )
            print(f"  Checkpoint saved: {path}")

    if is_main_process():
        print("Training complete.")
        if args.wandb_project:
            wandb.finish()

    if world_size > 1:
        dist.destroy_process_group()


if __name__ == "__main__":
    main()